name: jbok_info

services:
  nginx:
    image: jbok_info-nginx:latest
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_data:/var/www/jbok.info
      - cert_data:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    secrets:
      - nginx_conf
      - nginx_default
      - nginx_renew
    networks:
      - intra
    depends_on:
      frontend:
        condition: service_completed_successfully
    restart: unless-stopped

  axum:
    image: jbok_info-axum:latest
    build:
      context: ./backend
    container_name: axum
    networks:
      - intra
    # depends_on:
      # sqlite:
        # condition: healthy
    restart: unless-stopped

  frontend:
    image: jbok_info-frontend:latest
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - static_data:/var/www/jbok.info:rw
    restart: on-failure

  # sqlite:
  #   image: jbok_info-sqlite:latest
  #   build:
  #     context: ./sqlite
  #   container_name: sqlite
  #   networks:
  #     - intra
  #   restart: unless-stopped

volumes:
  static_data:
    name: jbok_info-static_data
  cert_data:
    name: jbok_info-cert_data
    external: true
  # db_data:
    # name: jbok_info-db_data
    # external: true

secrets:
  nginx_conf:
    file: .secrets/nginx.conf
  nginx_default:
    file: .secrets/default.conf
  nginx_renew:
    file: .secrets/renew.conf

networks:
  intra:
    driver: bridge