name: jbok_info

services:
  nginx:
    image: jbok_info-nginx:latest
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_data:/var/www/jbok.info
      - /var/www/certbot:/var/www/certbot
    secrets:
      - nginx.conf
      - default.conf
      - renew.conf
      - ssl_cert
      - ssl_key
      - ssl_params
    networks:
      - intra
    depends_on:
      frontend:
        condition: service_completed_successfully
    restart: unless-stopped

  axum:
    image: jbok_info-axum:latest
    build:
      context: ./backend
    container_name: axum
    networks:
      - intra
    restart: unless-stopped

  frontend:
    image: jbok_info-frontend:latest
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - static_data:/var/www/jbok.info:rw
    restart: on-failure

secrets:
  # NGINX secrets
  nginx.conf:
    file: ${NGINX_CONF_PATH}/nginx.conf
  default.conf:
    file: ${NGINX_CONF_PATH}/default.conf
  renew.conf:
    file: ${NGINX_CONF_PATH}/renew.conf
  ssl_cert:
    file: ${JBOK_INFO_CERT_PATH}/fullchain.pem
  ssl_key:
    file: ${JBOK_INFO_CERT_PATH}/privkey.pem
  ssl_params:
    file: ${CERT_PARAM_PATH}/ssl-dhparams.pem

volumes:
  static_data:
    name: jbok_info-static_data

networks:
  intra:
    driver: bridge
